name: 'Custom GitHub Action - python build ad test'
description: 'A GitHub Action that takes an input of python version, configure and run test'
inputs:
  num:
    description: 'Enter the python version'
    required: true
    type: string
    default: "3.10"
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: |
          **/setup.cfg
          **/requirements*.txt
    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt -r test/requirements_test.txt
    - name: Linting project with flake8
      shell: bash
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run application
      shell: bash
      run: |
        cd src
        gunicorn --bind=0.0.0.0:8000 wsgi:app --daemon
    - name: Testing the project using pytest
      shell: bash
      run: |
        coverage run -m pytest  -v -s
        coverage report -m
        coverage html
      continue-on-error: true
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ inputs.PYTHON_VERSION }}
        path: htmlcov/index.html
      if: ${{ always() }}